class ServoraConstants {
  static const String appName = 'Servora.gh';
  static const String appTagline = 'Northern Marketplace & Artisan Trade Hub';
  
  // Base Backend API URL - Live Production Vercel Database & REST Server
  static const String baseUrl = 'https://servoragh-inky.vercel.app/api';
  static const String localBaseUrl = 'http://localhost:3000/api';
  static const String webBaseUrl = 'https://servoragh-inky.vercel.app';

  static const List<String> northernNeighborhoods = [
    'All Northern Ghana',
    'Sakasaka',
    'Nyohini',
    'Choggu',
    'Aboabo',
    'Dungu UDS',
    'Lamashegu',
    'Vittin',
    'Gumani',
    'Kalpohin',
    'Central Market',
    'Tamale Industrial Area',
    'Bolgatanga',
    'Wa Central',
  ];

  static List<Map<String, dynamic>> get categories => classifiedCategories;

  static const List<Map<String, dynamic>> classifiedCategories = [
    {
      'name': 'Vehicles',
      'slug': 'vehicles',
      'icon': '🚗',
      'adsCountText': '0 ads',
      'description': 'Cars, buses, motorbikes, heavy trucks, spare parts, and auto services.',
      'subcategories': [
        {'name': 'Cars', 'slug': 'cars'},
        {'name': 'Buses & Microbuses', 'slug': 'buses-microbuses'},
        {'name': 'Motorbikes & Scooters', 'slug': 'motorbikes-scooters'},
        {'name': 'Trucks & Trailers', 'slug': 'trucks-trailers'},
        {'name': 'Vehicle Parts & Accessories', 'slug': 'vehicle-parts-accessories'},
        {'name': 'Tractors & Farm Machinery', 'slug': 'tractors-farm-machinery'},
        {'name': 'Watercraft & Boats', 'slug': 'watercraft-boats'},
        {'name': 'Car Services & Mechanics', 'slug': 'car-services-mechanics'},
      ],
    },
    {
      'name': 'Property',
      'slug': 'property',
      'icon': '🏠',
      'adsCountText': '0 ads',
      'description': 'Houses for rent, plots for sale, commercial spaces, and short lets.',
      'subcategories': [
        {'name': 'Houses & Apartments for Rent', 'slug': 'houses-rent'},
        {'name': 'Houses & Apartments for Sale', 'slug': 'houses-sale'},
        {'name': 'Land & Plots for Sale', 'slug': 'land-plots-sale'},
        {'name': 'Commercial Property for Rent', 'slug': 'commercial-property-rent'},
        {'name': 'Commercial Property for Sale', 'slug': 'commercial-property-sale'},
        {'name': 'Short Let & Guest Houses', 'slug': 'short-let-guest-houses'},
        {'name': 'Event Venues & Centers', 'slug': 'event-venues'},
        {'name': 'Flatmates & Shared Rooms', 'slug': 'flatmates-shared-rooms'},
      ],
    },
    {
      'name': 'Phones & Tablets',
      'slug': 'phones-tablets',
      'icon': '📱',
      'adsCountText': '0 ads',
      'description': 'Smartphones, tablets, smartwatches, power banks, and accessories.',
      'subcategories': [
        {'name': 'Mobile Phones', 'slug': 'mobile-phones'},
        {'name': 'Tablets', 'slug': 'tablets'},
        {'name': 'Smartwatches & Trackers', 'slug': 'smartwatches-trackers'},
        {'name': 'Mobile Phone Accessories', 'slug': 'mobile-accessories'},
        {'name': 'Mobile Phone Repair & Unlock', 'slug': 'phone-repair-services'},
      ],
    },
    {
      'name': 'Electronics',
      'slug': 'electronics',
      'icon': '💻',
      'adsCountText': '0 ads',
      'description': 'Laptops, TVs, audio systems, solar inverters, cameras, and gaming.',
      'subcategories': [
        {'name': 'Laptops & Computers', 'slug': 'laptops-computers'},
        {'name': 'TV & DVD Equipment', 'slug': 'tv-dvd-equipment'},
        {'name': 'Audio & Music Systems', 'slug': 'audio-music-systems'},
        {'name': 'Computer Accessories', 'slug': 'computer-accessories'},
        {'name': 'Cameras & Camcorders', 'slug': 'cameras-camcorders'},
        {'name': 'Video Game Consoles', 'slug': 'video-game-consoles'},
        {'name': 'Solar Power & Inverters', 'slug': 'solar-power-inverters'},
        {'name': 'Security Systems & CCTV', 'slug': 'security-cctv'},
        {'name': 'Networking Products', 'slug': 'networking-products'},
      ],
    },
    {
      'name': 'Home, Furniture & Appliances',
      'slug': 'home-furniture-appliances',
      'icon': '🛋️',
      'adsCountText': '0 ads',
      'description': 'Sofas, beds, fridges, air conditioners, kitchenware, and decor.',
      'subcategories': [
        {'name': 'Furniture', 'slug': 'furniture'},
        {'name': 'Home Appliances', 'slug': 'home-appliances'},
        {'name': 'Kitchen Appliances & Dining', 'slug': 'kitchen-appliances'},
        {'name': 'Beds, Mattresses & Bedding', 'slug': 'beds-mattresses'},
        {'name': 'Home Decor & Lighting', 'slug': 'home-decor-lighting'},
        {'name': 'Garden & Outdoor Living', 'slug': 'garden-outdoor'},
        {'name': 'Office Furniture', 'slug': 'office-furniture'},
        {'name': 'Curtains & Blinds', 'slug': 'curtains-blinds'},
        {'name': 'Cleaning & Janitorial Supplies', 'slug': 'cleaning-supplies'},
      ],
    },
    {
      'name': 'Fashion',
      'slug': 'fashion',
      'icon': '👕',
      'adsCountText': '0 ads',
      'description': 'Royal Fugu smocks, men & women clothing, shoes, bags, and jewelry.',
      'subcategories': [
        {'name': 'Traditional Fugu & Northern Wear', 'slug': 'traditional-fugu-northern-wear'},
        {'name': 'Clothing', 'slug': 'clothing'},
        {'name': 'Shoes & Footwear', 'slug': 'shoes-footwear'},
        {'name': 'Bags & Luggage', 'slug': 'bags-luggage'},
        {'name': 'Jewelry & Watches', 'slug': 'jewelry-watches'},
        {'name': 'Fashion Accessories', 'slug': 'fashion-accessories'},
        {'name': 'Wedding & Ceremonial Wear', 'slug': 'wedding-ceremonial-wear'},
        {'name': 'Fabrics & Sewing Materials', 'slug': 'fabrics-sewing'},
        {'name': 'Tailoring Services', 'slug': 'tailoring-services'},
      ],
    },
    {
      'name': 'Beauty & Personal Care',
      'slug': 'beauty-personal-care',
      'icon': '✨',
      'adsCountText': '0 ads',
      'description': 'Shea butter products, skincare, hair care, perfumes, and makeup.',
      'subcategories': [
        {'name': 'Organic Shea Butter & Cosmetics', 'slug': 'shea-butter-cosmetics'},
        {'name': 'Skincare & Body Care', 'slug': 'skincare-body-care'},
        {'name': 'Hair Care & Wigs', 'slug': 'hair-care-wigs'},
        {'name': 'Fragrances & Perfumes', 'slug': 'fragrances-perfumes'},
        {'name': 'Makeup & Cosmetics', 'slug': 'makeup-cosmetics'},
        {'name': 'Barbing & Salon Equipment', 'slug': 'barbing-salon-equipment'},
        {'name': 'Health & Wellness Supplies', 'slug': 'health-wellness'},
      ],
    },
    {
      'name': 'Services',
      'slug': 'services',
      'icon': '🛠️',
      'adsCountText': '0 ads',
      'description': 'Artisan trades, electrical, plumbing, catering, IT, and event planning.',
      'subcategories': [
        {'name': 'Artisan & Trade Services', 'slug': 'artisan-trade-services'},
        {'name': 'Electrical & Solar Installation', 'slug': 'electrical-solar-services'},
        {'name': 'Plumbing & Borehole Drilling', 'slug': 'plumbing-borehole-services'},
        {'name': 'Catering & Event Planning', 'slug': 'catering-event-services'},
        {'name': 'IT, Web & Graphic Design', 'slug': 'it-design-services'},
        {'name': 'Logistics & Haulage', 'slug': 'logistics-haulage-services'},
        {'name': 'Legal, Accounting & Business Consultancy', 'slug': 'legal-consultancy-services'},
        {'name': 'Cleaning & Fumigation', 'slug': 'cleaning-fumigation-services'},
        {'name': 'Classes, Tutoring & Training', 'slug': 'classes-tutoring-services'},
      ],
    },
    {
      'name': 'Repair & Construction',
      'slug': 'repair-construction',
      'icon': '🧱',
      'adsCountText': '0 ads',
      'description': 'Building contractors, cement, roofing sheets, masonry, and welding.',
      'subcategories': [
        {'name': 'Building Materials & Cement', 'slug': 'building-materials-cement'},
        {'name': 'Roofing Sheets & Trusses', 'slug': 'roofing-sheets-trusses'},
        {'name': 'Masonry & Concrete Works', 'slug': 'masonry-concrete'},
        {'name': 'Welding, Fabrication & Metalwork', 'slug': 'welding-fabrication-metalwork'},
        {'name': 'Carpentry & Woodworking', 'slug': 'carpentry-woodworking'},
        {'name': 'Painting & Tiling Services', 'slug': 'painting-tiling'},
        {'name': 'Architectural & Surveying Services', 'slug': 'architectural-surveying'},
      ],
    },
    {
      'name': 'Commercial Equipment & Tools',
      'slug': 'commercial-equipment-tools',
      'icon': '⚙️',
      'adsCountText': '0 ads',
      'description': 'Generators, power drills, grinding mills, water pumps, and rentals.',
      'subcategories': [
        {'name': 'Heavy Machinery & Excavators', 'slug': 'heavy-machinery-excavators'},
        {'name': 'Generators & Power Plants', 'slug': 'generators-power-plants'},
        {'name': 'Tool Rentals & Power Tools', 'slug': 'tool-rentals-power-tools'},
        {'name': 'Industrial Pumps & Tanks', 'slug': 'industrial-pumps-tanks'},
        {'name': 'Agro-Processing Machines & Mills', 'slug': 'agro-processing-machines'},
        {'name': 'Store & Supermarket Equipment', 'slug': 'store-supermarket-equipment'},
      ],
    },
    {
      'name': 'Leisure & Activities',
      'slug': 'leisure-activities',
      'icon': '🎯',
      'adsCountText': '0 ads',
      'description': 'Sports gear, musical instruments, books, bicycles, and travel deals.',
      'subcategories': [
        {'name': 'Sports Gear & Fitness', 'slug': 'sports-gear-fitness'},
        {'name': 'Musical Instruments', 'slug': 'musical-instruments'},
        {'name': 'Bicycles & Cycling', 'slug': 'bicycles-cycling'},
        {'name': 'Books, Stationery & Games', 'slug': 'books-stationery-games'},
        {'name': 'Camping & Outdoor Gear', 'slug': 'camping-outdoor-gear'},
      ],
    },
    {
      'name': 'Babies & Kids',
      'slug': 'babies-kids',
      'icon': '👶',
      'adsCountText': '0 ads',
      'description': 'Baby clothes, strollers, toys, school supplies, and children furniture.',
      'subcategories': [
        {'name': 'Baby Clothing & Shoes', 'slug': 'baby-clothing-shoes'},
        {'name': 'Baby Gear & Strollers', 'slug': 'baby-gear-strollers'},
        {'name': 'Toys & Video Games for Kids', 'slug': 'kids-toys-games'},
        {'name': 'Children Furniture & Cribs', 'slug': 'children-furniture'},
        {'name': 'School Supplies & Bags', 'slug': 'school-supplies'},
      ],
    },
    {
      'name': 'Food, Agriculture & Farming',
      'slug': 'food-agriculture-farming',
      'icon': '🌾',
      'adsCountText': '0 ads',
      'description': 'Grains, yam tubers, poultry, irrigation pumps, fertilizers, and produce.',
      'subcategories': [
        {'name': 'Farm Produce & Grains', 'slug': 'farm-produce-grains'},
        {'name': 'Tubers, Yam & Vegetables', 'slug': 'tubers-yam-vegetables'},
        {'name': 'Fertilizers & Agro-Chemicals', 'slug': 'fertilizers-agrochemicals'},
        {'name': 'Irrigation Systems & Pumps', 'slug': 'irrigation-systems-pumps'},
        {'name': 'Animal Feed & Supplements', 'slug': 'animal-feed-supplements'},
        {'name': 'Processed Food & Spices', 'slug': 'processed-food-spices'},
      ],
    },
    {
      'name': 'Animals & Pets',
      'slug': 'animals-pets',
      'icon': '🐂',
      'adsCountText': '0 ads',
      'description': 'Cattle, sheep, goats, poultry, dogs, livestock feed, and vet services.',
      'subcategories': [
        {'name': 'Cattle, Sheep & Goats', 'slug': 'cattle-sheep-goats'},
        {'name': 'Poultry & Birds', 'slug': 'poultry-birds'},
        {'name': 'Dogs & Puppies', 'slug': 'dogs-puppies'},
        {'name': 'Fish & Aquaculture', 'slug': 'fish-aquaculture'},
        {'name': 'Veterinary & Pet Care Services', 'slug': 'vet-pet-services'},
      ],
    },
    {
      'name': 'Jobs',
      'slug': 'jobs',
      'icon': '💼',
      'adsCountText': '0 ads',
      'description': 'Full-time vacancies, part-time jobs, artisan gigs, and driver roles.',
      'subcategories': [
        {'name': 'Driver & Security Jobs', 'slug': 'driver-security-jobs'},
        {'name': 'Artisan & Trade Vacancies', 'slug': 'artisan-trade-vacancies'},
        {'name': 'Sales & Customer Service Jobs', 'slug': 'sales-customer-service-jobs'},
        {'name': 'Teaching & Academic Jobs', 'slug': 'teaching-academic-jobs'},
        {'name': 'IT & Telecoms Jobs', 'slug': 'it-telecoms-jobs'},
        {'name': 'Accounting & Finance Vacancies', 'slug': 'accounting-finance-jobs'},
      ],
    },
    {
      'name': 'Seeking Work - CVs',
      'slug': 'seeking-work-cvs',
      'icon': '📄',
      'adsCountText': '0 ads',
      'description': 'Profiles of skilled artisans, drivers, teachers, and graduates seeking work.',
      'subcategories': [
        {'name': 'Artisan & Technical CVs', 'slug': 'artisan-technical-cvs'},
        {'name': 'Driver & Logistics CVs', 'slug': 'driver-logistics-cvs'},
        {'name': 'Administrative & Sales CVs', 'slug': 'admin-sales-cvs'},
        {'name': 'Teaching & Graduate CVs', 'slug': 'teaching-graduate-cvs'},
      ],
    },
    {
      'name': 'Business & Industry',
      'slug': 'business-industry',
      'icon': '🏢',
      'adsCountText': '0 ads',
      'description': 'Business partnerships, wholesale trade goods, factory machinery, and licenses.',
      'subcategories': [
        {'name': 'Wholesale & Bulk Goods', 'slug': 'wholesale-bulk-goods'},
        {'name': 'Factory & Processing Plant Equipment', 'slug': 'factory-plant-equipment'},
        {'name': 'Businesses for Sale & Partnerships', 'slug': 'businesses-for-sale'},
        {'name': 'Commercial Printing & Packaging', 'slug': 'commercial-printing-packaging'},
      ],
    },
  ];

  /// Get subcategories array for a specific category name
  static List<Map<String, String>> getSubcategories(String categoryName) {
    final cat = classifiedCategories.firstWhere(
      (c) => c['name'] == categoryName,
      orElse: () => classifiedCategories[0],
    );
    final List<dynamic> subs = cat['subcategories'] ?? [];
    return subs.map((s) => {'name': s['name'].toString(), 'slug': s['slug'].toString()}).toList();
  }
}
