import { PrismaClient, ItemCondition, SellerType, ProductListingStatus } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding realistic mock products & services for ALL 18 Universal Categories into PostgreSQL...");

  const admin = await prisma.user.findFirst({ where: { role: "ADMIN" } });
  const adminId = admin?.id || null;

  const mockItems = [
    // 1. Food & Dining
    {
      id: "mock-item-food-01",
      title: "Northern Ghana Smoked Guinea Fowl & Fried Yam Platter",
      slug: "northern-ghana-smoked-guinea-fowl-yam-platter",
      description: "Freshly seasoned charcoal-grilled Northern guinea fowl served with hot pepper sauce, fried yam chips, and fresh onions. Available for instant delivery in Tamale.",
      category: "Food & Dining",
      subCategory: "Local Northern Delicacies",
      condition: ItemCondition.BRAND_NEW,
      price: 120.0,
      originalPrice: 150.0,
      isNegotiable: false,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Central Market, Tamale",
      deliveryOptions: ["LOCAL_DELIVERY", "PICKUP"],
      sellerType: SellerType.GUEST,
      guestName: "Hajia Mariam's Northern Kitchen",
      guestPhone: "+233244112233",
      guestWhatsApp: "+233244112233",
      isGuestVerified: true,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 2. Retail & Shopping
    {
      id: "mock-item-retail-02",
      title: "Wholesale Fast Charger Bundle (Samsung & iPhone 20W PD Type-C)",
      slug: "wholesale-fast-charger-bundle-samsung-iphone-20w",
      description: "Original 20W USB-C Power Delivery super-fast charging adapters with braider cables. Wholesale pack of 10 units for mobile shops in Bolgatanga and Tamale.",
      category: "Retail & Shopping",
      subCategory: "Mobile Accessories",
      condition: ItemCondition.BRAND_NEW,
      price: 450.0,
      originalPrice: 600.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Aboabo Market, Tamale",
      deliveryOptions: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
      sellerType: SellerType.REGISTERED_USER,
      sellerId: adminId,
      status: ProductListingStatus.ACTIVE,
      isFeatured: false,
    },

    // 3. Professional Services
    {
      id: "mock-item-prof-03",
      title: "Architectural & Civil Structural Building Blueprint Plan Service",
      slug: "architectural-structural-building-blueprint-plan-service",
      description: "Certified architectural drawings, 3D exterior renders, structural engineering calculations, and EPA documentation for residential & commercial sites in Northern Ghana.",
      category: "Professional Services",
      subCategory: "Architectural & Engineering Services",
      condition: ItemCondition.BRAND_NEW,
      price: 2500.0,
      originalPrice: 3200.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Sakasaka, Tamale",
      deliveryOptions: ["DIGITAL_DELIVERY", "PICKUP"],
      sellerType: SellerType.REGISTERED_USER,
      sellerId: adminId,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 4. Home & Property
    {
      id: "mock-item-home-04",
      title: "Modern 2-Bedroom Self-Contained Apartment for Rent in Kalpohin Estate",
      slug: "modern-2-bedroom-self-contained-apartment-kalpohin-estate",
      description: "Newly built 2-bedroom walled house with private prepaid meter, water storage tank, tiled floors, and spacious compound in serene Kalpohin Residential Area.",
      category: "Home & Property",
      subCategory: "Residential Property Renting",
      condition: ItemCondition.BRAND_NEW,
      price: 850.0,
      originalPrice: 1000.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Kalpohin Estate, Tamale",
      deliveryOptions: ["INSPECTION_VISIT"],
      sellerType: SellerType.GUEST,
      guestName: "Alhaji Fuseini Real Estate",
      guestPhone: "+233208889900",
      guestWhatsApp: "+233208889900",
      isGuestVerified: true,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 5. Automotive & Transport
    {
      id: "mock-item-auto-05",
      title: "Toyota Hilux Double Cabin Pickup Truck (2021 Model - 4x4)",
      slug: "toyota-hilux-double-cabin-pickup-truck-2021-4x4",
      description: "Heavy duty 2.8L Diesel 4WD pickup truck. Air conditioning ice-cold, custom bullbar, tow bar, and clean engine. Perfect for farm and construction terrain.",
      category: "Automotive & Transport",
      subCategory: "Commercial Vehicles & Pickups",
      condition: ItemCondition.USED_LIKE_NEW,
      price: 195000.0,
      originalPrice: 210000.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Sakasaka, Tamale",
      deliveryOptions: ["PICKUP", "LOCAL_DELIVERY"],
      sellerType: SellerType.REGISTERED_USER,
      sellerId: adminId,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 6. Health & Wellness
    {
      id: "mock-item-health-06",
      title: "Pure Raw Unrefined Northern Sheabutter (25kg Wholesale Bucket)",
      slug: "pure-raw-unrefined-northern-sheabutter-25kg-bucket",
      description: "100% natural Grade-A organic unrefined ivory sheabutter hand-processed by womens cooperative in Wa, Upper West Region. Excellent for cosmetics & hair.",
      category: "Health & Wellness",
      subCategory: "Natural Skincare & Wellness",
      condition: ItemCondition.BRAND_NEW,
      price: 320.0,
      originalPrice: 400.0,
      isNegotiable: false,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1608248597266-c89050d26859?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Wa, Upper West Region",
      deliveryOptions: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
      sellerType: SellerType.GUEST,
      guestName: "Wa Womens Sheabutter Guild",
      guestPhone: "+233245009988",
      guestWhatsApp: "+233245009988",
      isGuestVerified: true,
      status: ProductListingStatus.ACTIVE,
      isFeatured: false,
    },

    // 7. Beauty & Personal Care
    {
      id: "mock-item-beauty-07",
      title: "Professional Bridal Hair Styling & Glam Makeup Package",
      slug: "professional-bridal-hair-styling-glam-makeup-package",
      description: "Complete bridal makeover service including HD airbrush makeup, wig installation, headwrap (Gele/Fugu) styling, and touchup kit for weddings in Tamale.",
      category: "Beauty & Personal Care",
      subCategory: "Bridal Makeup & Hair",
      condition: ItemCondition.BRAND_NEW,
      price: 1200.0,
      originalPrice: 1500.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Choggu, Tamale",
      deliveryOptions: ["ON_SITE_SERVICE"],
      sellerType: SellerType.GUEST,
      guestName: "Glamour Northern Beauty Studio",
      guestPhone: "+233277889900",
      guestWhatsApp: "+233277889900",
      isGuestVerified: true,
      status: ProductListingStatus.ACTIVE,
      isFeatured: false,
    },

    // 8. Education & Training
    {
      id: "mock-item-edu-08",
      title: "Practical Solar Energy & 3-Phase Electrical Installation Training Course",
      slug: "practical-solar-energy-electrical-installation-training-course",
      description: "4-week intensive hands-on workshop covering solar panel sizing, inverter wiring, lithium battery banks, borehole pump control boxes, and Ghana Standards Authority compliance.",
      category: "Education & Training",
      subCategory: "Technical & Vocational Training",
      condition: ItemCondition.BRAND_NEW,
      price: 850.0,
      originalPrice: 1200.0,
      isNegotiable: false,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Dungu UDS Campus, Tamale",
      deliveryOptions: ["IN_PERSON_CLASS"],
      sellerType: SellerType.REGISTERED_USER,
      sellerId: adminId,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 9. Agriculture & Produce
    {
      id: "mock-item-agri-09",
      title: "50kg Bag of Premium Savannah Parboiled White Rice (Northern Harvest)",
      slug: "50kg-bag-premium-savannah-parboiled-white-rice",
      description: "Stone-free long-grain parboiled white rice directly harvested from irrigated rice fields in Botanga and Nasia. Crisp texture, high swelling capacity.",
      category: "Agriculture & Produce",
      subCategory: "Grains & Cereals",
      condition: ItemCondition.BRAND_NEW,
      price: 680.0,
      originalPrice: 750.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Aboabo Market, Tamale",
      deliveryOptions: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
      sellerType: SellerType.GUEST,
      guestName: "Nasia Grain Farmers Co-op",
      guestPhone: "+233209998877",
      guestWhatsApp: "+233209998877",
      isGuestVerified: true,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 10. Construction & Heavy Duty
    {
      id: "mock-item-const-10",
      title: "5.5KVA Heavy Duty Silent Diesel Generator Rental & Site Power Service",
      slug: "5kva-heavy-duty-silent-diesel-generator-rental",
      description: "Low-noise diesel generator available for 24-hour or weekly rental. Supplied with transfer switch and heavy cabling for construction sites and commercial events.",
      category: "Construction & Heavy Duty",
      subCategory: "Generator & Heavy Equipment Rentals",
      condition: ItemCondition.USED_LIKE_NEW,
      price: 350.0,
      originalPrice: 450.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Sakasaka, Tamale",
      deliveryOptions: ["LOCAL_DELIVERY", "PICKUP"],
      sellerType: SellerType.REGISTERED_USER,
      sellerId: adminId,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 11. Travel & Hospitality
    {
      id: "mock-item-travel-11",
      title: "Mole National Park Weekend Safari & Ecolodge Tour Package",
      slug: "mole-national-park-weekend-safari-ecolodge-tour-package",
      description: "2-Day guided wildlife safari at Mole National Park including AC 4x4 transport from Tamale Airport, Zaina Ecolodge accommodation, elephant walking safari, and Larabanga mosque visit.",
      category: "Travel & Hospitality",
      subCategory: "Safari Tours & Lodging",
      condition: ItemCondition.BRAND_NEW,
      price: 1800.0,
      originalPrice: 2200.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Tamale / Mole National Park",
      deliveryOptions: ["GUIDED_TOUR"],
      sellerType: SellerType.GUEST,
      guestName: "Savannah Expedition Tours",
      guestPhone: "+233246665544",
      guestWhatsApp: "+233246665544",
      isGuestVerified: true,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 12. Events & Entertainment
    {
      id: "mock-item-events-12",
      title: "500-Capacity Outdoor Event Canopy, Sound System & Lighting Package",
      slug: "500-capacity-outdoor-event-canopy-sound-lighting-package",
      description: "Full event rental setup: 4 high-peak marquee canopies, 500 padded chiavari chairs, 40 round banquet tables, 4000W JBL PA system, wireless mics, and ambient stage lighting.",
      category: "Events & Entertainment",
      subCategory: "Event Rentals & PA Systems",
      condition: ItemCondition.BRAND_NEW,
      price: 3500.0,
      originalPrice: 4200.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Nyohini, Tamale",
      deliveryOptions: ["ON_SITE_SETUP"],
      sellerType: SellerType.REGISTERED_USER,
      sellerId: adminId,
      status: ProductListingStatus.ACTIVE,
      isFeatured: false,
    },

    // 13. Fashion & Custom Tailoring
    {
      id: "mock-item-fashion-13",
      title: "Handwoven Royal Dagbon Heavy Cotton Fugu (Smock - Size XL)",
      slug: "handwoven-royal-dagbon-heavy-cotton-fugu-smock",
      description: "Authentic handspun Northern Ghana heavy cotton fugu. Traditional indigo blue and white stripes with intricate neck embroidery and matching cap.",
      category: "Fashion & Custom Tailoring",
      subCategory: "Northern Smocks (Fugu)",
      condition: ItemCondition.BRAND_NEW,
      price: 520.0,
      originalPrice: 650.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Nyohini, Tamale",
      deliveryOptions: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
      sellerType: SellerType.GUEST,
      guestName: "Master Yussif Fugu Weavers",
      guestPhone: "+233243332211",
      guestWhatsApp: "+233243332211",
      isGuestVerified: true,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 14. Technology & Digital Services
    {
      id: "mock-item-tech-14",
      title: "HP EliteBook 840 G8 Core i7 Laptop (16GB RAM, 512GB NVMe SSD)",
      slug: "hp-elitebook-840-g8-core-i7-laptop-16gb-ram",
      description: "Sleek aluminum ultra-slim business laptop. 11th Gen Intel Core i7, 16GB DDR4 RAM, 512GB SSD, fingerprint reader, backlit keyboard, 6-hour battery health.",
      category: "Technology & Digital Services",
      subCategory: "Laptops & Computers",
      condition: ItemCondition.USED_LIKE_NEW,
      price: 4600.0,
      originalPrice: 5200.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Central Market, Tamale",
      deliveryOptions: ["PICKUP", "LOCAL_DELIVERY", "SHIPPING"],
      sellerType: SellerType.REGISTERED_USER,
      sellerId: adminId,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },

    // 15. Legal & Government Advisory
    {
      id: "mock-item-legal-15",
      title: "RGD Business Name Registration & GRA Tax Compliance Filing Service",
      slug: "rgd-business-name-registration-gra-tax-compliance-filing",
      description: "Fast-track Registrar General Department (RGD) business registration, TIN generation, GRA tax clearance certificate, and SSNIT employer registration in Tamale.",
      category: "Legal & Government Advisory",
      subCategory: "Business Registration & Corporate Advisory",
      condition: ItemCondition.BRAND_NEW,
      price: 650.0,
      originalPrice: 850.0,
      isNegotiable: false,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Sakasaka, Tamale",
      deliveryOptions: ["DIGITAL_DELIVERY", "IN_PERSON_CLASS"],
      sellerType: SellerType.GUEST,
      guestName: "Savannah Corporate Consult",
      guestPhone: "+233201122334",
      guestWhatsApp: "+233201122334",
      isGuestVerified: true,
      status: ProductListingStatus.ACTIVE,
      isFeatured: false,
    },

    // 16. Finance & Accounting
    {
      id: "mock-item-finance-16",
      title: "SME Mobile Money Escrow Bookkeeping & Financial Record Setup",
      slug: "sme-mobile-money-escrow-bookkeeping-financial-record-setup",
      description: "Customized bookkeeping spreadsheet setup, MoMo transaction reconciliation, daily cash flow tracker, and profit margin analysis for retailers & artisans.",
      category: "Finance & Accounting",
      subCategory: "Small Business Bookkeeping",
      condition: ItemCondition.BRAND_NEW,
      price: 450.0,
      originalPrice: 600.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Aboabo Market, Tamale",
      deliveryOptions: ["DIGITAL_DELIVERY"],
      sellerType: SellerType.REGISTERED_USER,
      sellerId: adminId,
      status: ProductListingStatus.ACTIVE,
      isFeatured: false,
    },

    // 17. Jobs & Freelance Gigs
    {
      id: "mock-item-jobs-17",
      title: "Licensed Commercial Heavy Truck Driver (Ghana License C & E Holder)",
      slug: "licensed-commercial-heavy-truck-driver-ghana-license-ce",
      description: "Experienced long-distance haulage driver with 8 years clean record operating tipper trucks, cargo vans, and delivery fleets across Northern Ghana routes.",
      category: "Jobs & Freelance Gigs",
      subCategory: "Driver & Logistics Gigs",
      condition: ItemCondition.BRAND_NEW,
      price: 1800.0,
      originalPrice: 2000.0,
      isNegotiable: true,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Lamashegu, Tamale",
      deliveryOptions: ["ON_SITE_SERVICE"],
      sellerType: SellerType.GUEST,
      guestName: "Ibrahim Alhassan (Driver)",
      guestPhone: "+233241199887",
      guestWhatsApp: "+233241199887",
      isGuestVerified: true,
      status: ProductListingStatus.ACTIVE,
      isFeatured: false,
    },

    // 18. Community & NGOs
    {
      id: "mock-item-community-18",
      title: "Community Water Borehole Maintenance & Solar Pump Guild Support Call",
      slug: "community-water-borehole-maintenance-solar-pump-support-call",
      description: "Guild initiative offering subsidized inspection and desilting for rural solar-powered community boreholes in Bolgatanga and Tamale outskirts.",
      category: "Community & NGOs",
      subCategory: "Community Water & Guild Initiatives",
      condition: ItemCondition.BRAND_NEW,
      price: 0.0,
      originalPrice: null,
      isNegotiable: false,
      currency: "GHS",
      images: [
        "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=600&auto=format&fit=crop&q=80",
      ],
      area: "Bolgatanga / Tamale Outskirts",
      deliveryOptions: ["ON_SITE_SERVICE"],
      sellerType: SellerType.REGISTERED_USER,
      sellerId: adminId,
      status: ProductListingStatus.ACTIVE,
      isFeatured: true,
    },
  ];

  for (const item of mockItems) {
    await prisma.productListing.upsert({
      where: { id: item.id },
      update: {
        title: item.title,
        slug: item.slug,
        description: item.description,
        category: item.category,
        subCategory: item.subCategory,
        condition: item.condition,
        price: item.price,
        originalPrice: item.originalPrice,
        isNegotiable: item.isNegotiable,
        currency: item.currency,
        images: item.images,
        area: item.area,
        deliveryOptions: item.deliveryOptions,
        sellerType: item.sellerType,
        sellerId: item.sellerId || null,
        guestName: item.guestName || null,
        guestPhone: item.guestPhone || null,
        guestWhatsApp: item.guestWhatsApp || null,
        isGuestVerified: item.isGuestVerified || false,
        status: item.status,
        isFeatured: item.isFeatured,
      },
      create: {
        id: item.id,
        title: item.title,
        slug: item.slug,
        description: item.description,
        category: item.category,
        subCategory: item.subCategory,
        condition: item.condition,
        price: item.price,
        originalPrice: item.originalPrice,
        isNegotiable: item.isNegotiable,
        currency: item.currency,
        images: item.images,
        area: item.area,
        deliveryOptions: item.deliveryOptions,
        sellerType: item.sellerType,
        sellerId: item.sellerId || null,
        guestName: item.guestName || null,
        guestPhone: item.guestPhone || null,
        guestWhatsApp: item.guestWhatsApp || null,
        isGuestVerified: item.isGuestVerified || false,
        status: item.status,
        isFeatured: item.isFeatured,
      },
    });
    console.log(` ✅ Seeded item for category: "${item.category}" -> ${item.title}`);
  }

  console.log("🎉 Successfully seeded mock products & services across all 18 Universal Categories!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
